org: ivoveliz
app: test
service: transelec-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        -  arn:aws:dynamodb:us-west-2:200364214857:table/TranselecDB_Oficina

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get

  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get

  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: get

  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post

  deleteTask:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete


resources:
  Resources:
    transelecDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TranselecDB_Oficina
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH